### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by 0x6c66**
fixed the link to elements and added pop

### CODE REVIEW

**Comment by fopina** [comment]
Thanks!

**Comment by fopina** [comment]
have you managed to compile @4m4rOk ?

missing some ../../config.h which I assume defines the SETUP_API_ID macro...

**Comment by milsirhc** [comment]
same issue here too.

missing some ../../config.h

**Comment by pallavi-webonise** [comment]
I am also facing same issue... ../../config.h file not found and implicit declaration of SETUP_API_ID function is invalid in c99 ..
Did you get any solution..?

**Comment by pallavi-kamat** [comment]
I am also facing same issue... ../../config.h file not found and implicit declaration of SETUP_API_ID function is invalid in c99 ..
Did you get any solution..?

**Comment by xcriss** [comment]
same issue here too.

missing some ../../config.h

**Comment by kamitchell** [comment]
For the config.h issue, see #17, which provides a sample config.h which should be filled in with your own API id and hash.

**Pull request closed without merging**
